import type { Metadata } from "next";
import { Geist, Geist_Mono, Raleway } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ClerkProvider, Show, SignInButton, UserButton } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/theme-provider";
import { Button } from "@/components/ui/button";

const raleway = Raleway({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn("font-sans", raleway.variable)}
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-7xl mx-auto flex items-center justify-center min-h-screen`}
      >
        <ClerkProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Show when="signed-in">{children}</Show>
            <Show when="signed-out">
              <SignInButton mode="modal">
                <Button>Sign in</Button>
              </SignInButton>
            </Show>
          </ThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
